# -*- coding: utf-8 -*-
"""課題_クラス.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wp1L58ABT-AQvEyz6JAvM_lwq2Gh615F
"""

class Human:
  def __init__(self, name, age):
    self.name = name
    self.age = age
  def printinfo(self):
    print(self.name)
    print(self.age)

person = Human("佐藤",35)
person.printinfo()