# -*- coding: utf-8 -*-
"""課題if.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NKWjrWwI2O21L667X9C7OoaQdZRsebeM
"""

var=15
if var%3==0 and var%5==0:
  print("FizzBuzz")
elif var%3==0:
  print("Fizz")
elif var%5==0:
  print("Buzz")
else :
  print(var)