# -*- coding: utf-8 -*-
"""課題_関数.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iNxqNQrNcKQr0eWtdbMn7NZKuYBqeedq
"""

def calc_price(price, tax):
  total = price * tax
  return total

print(calc_price(2000,1.1))