# -*- coding: utf-8 -*-
"""課題_四則演算.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bTrxPDj0-ADGqxp-XUGeHDj_gAnYVTw4
"""

upper=10
lower=20
height=5

area=(upper+lower)*height/2
print(str(area)+"cm²")