# -*- coding: utf-8 -*-
"""課題_変数スコープ.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jqUjHjqE6dUwQS58f3j-M5kjWfsnVicT
"""

price1 = 100                    #こっちはグローバル
price2 = 200

def total(price_1, price_2):    #名前同じだと違いが分かりにくいのでローカル用としてちょっと変数名を変える
    tax = 1.1
    return (price_1 + price_2) * tax

print(total(price1, price2))