# -*- coding: utf-8 -*-
"""課題_総合.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l3G87glI8GfEqSYlqF1y0Y7HTrp3mqHN
"""

#登場人物
dic = {"田中": 21, "佐藤": 20, "山田": 18, "鈴木": 25}

#クラスを作成
class Human:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def check_adult(self):
    if self.age >= 20:
      print(f"{self.name}は大人です")
    else:
      print(f"{self.name}は大人ではありません")

#クラスのインスタンスを複数作成しリストに追加
def add_list(t_list, target):
  t_list.append(target)

names = []  #名前用ﾘｽﾄ
ages = []   #年齢用ﾘｽﾄ
for t_name, t_age in dic.items(): #クラスの中のname,ageとスコープを意識したつもり
  person = Human(t_name, t_age)
  add_list(names, person.name)
  add_list(ages, person.age)

#リストの要素分だけ判定⇒出力
i=0
while i < len(names):
  person = Human(names[i], ages[i])
  person.check_adult()
  i += 1