# -*- coding: utf-8 -*-
"""課題_繰り返し.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cHYHRXpqECcccAutJC8BjAKNM27OB5kE
"""

list = ["水","金","地","火","木","土","天","海","冥"]
for planet in list:
  print(planet)

i = 0
while i < len(list):
  print(list[i])
  i=i+1